-- MySQL Script generated by MySQL Workbench
-- Sat May 28 14:36:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo` DEFAULT CHARACTER SET utf8 ;
USE `todo` ;

-- -----------------------------------------------------
-- Table `todo`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` NVARCHAR(50) NULL,
  `surname` NVARCHAR(50) NULL,
  `login` NVARCHAR(10) NULL,
  `password` NVARCHAR(20) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo`.`projects` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `project_name` NVARCHAR(50) NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo`.`status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `status_name` INT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo`.`priority` (
  `priority_id` INT NOT NULL AUTO_INCREMENT,
  `priority_name` INT NULL,
  PRIMARY KEY (`priority_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo`.`tasks` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `task_name` NVARCHAR(50) NULL,
  `date` DATE NULL,
  `description` NVARCHAR(50) NULL,
  `status_id` INT NOT NULL,
  `priority_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`task_id`, `status_id`, `priority_id`, `project_id`),
  INDEX `fk_tasks_status1_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_tasks_priotiy1_idx` (`priority_id` ASC) VISIBLE,
  INDEX `fk_tasks_projects1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `todo`.`status` (`status_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tasks_priotiy1`
    FOREIGN KEY (`priority_id`)
    REFERENCES `todo`.`priority` (`priority_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tasks_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `todo`.`projects` (`project_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`user_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo`.`user_task` (
  `user_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `task_id`),
  INDEX `fk_user_project_tasks1_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_project_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `todo`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_project_tasks1`
    FOREIGN KEY (`task_id`)
    REFERENCES `todo`.`tasks` (`task_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
