-- MySQL Script generated by MySQL Workbench
-- Mon May 23 00:56:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo` DEFAULT CHARACTER SET utf8 ;
USE `todo` ;

-- -----------------------------------------------------
-- Table `todo`.`sub_tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo`.`sub_tasks` (
  `sub_task_id` INT NOT NULL AUTO_INCREMENT,
  `sub_taskname` NVARCHAR(50) NULL,
  `date` DATE NULL,
  `priority` INT NULL,
  PRIMARY KEY (`sub_task_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo`.`tasks` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `task_name` NVARCHAR(50) NULL,
  `date` DATE NULL,
  `priority` INT NULL,
  `sub_task_id` INT NOT NULL,
  PRIMARY KEY (`task_id`, `sub_task_id`),
  INDEX `fk_tasks_sub_tasks1_idx` (`sub_task_id` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_sub_tasks1`
    FOREIGN KEY (`sub_task_id`)
    REFERENCES `todo`.`sub_tasks` (`sub_task_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo`.`projects` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `project_name` NVARCHAR(50) NULL,
  `task_id` INT NOT NULL,
  `sub_task_id` INT NOT NULL,
  PRIMARY KEY (`project_id`, `task_id`, `sub_task_id`),
  INDEX `fk_projects_tasks1_idx` (`task_id` ASC, `sub_task_id` ASC) VISIBLE,
  CONSTRAINT `fk_projects_tasks1`
    FOREIGN KEY (`task_id` , `sub_task_id`)
    REFERENCES `todo`.`tasks` (`task_id` , `sub_task_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` NVARCHAR(50) NULL,
  `surname` NVARCHAR(50) NULL,
  `login` NVARCHAR(10) NULL,
  `password` NVARCHAR(20) NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `project_id`),
  INDEX `fk_user_projects1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `todo`.`projects` (`project_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
